"""add users table + user_id scoping

Revision ID: 27ba4ca3941b
Revises: 86d162045657
Create Date: 2026-06-25 10:27:55.840988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '27ba4ca3941b'
down_revision: Union[str, Sequence[str], None] = '86d162045657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('is_player_move', sa.Integer(), nullable=False),
    sa.Column('fen_before', sa.Text(), nullable=False),
    sa.Column('move_uci', sa.String(), nullable=False),
    sa.Column('move_san', sa.String(), nullable=False),
    sa.Column('eval_before', sa.Float(), nullable=True),
    sa.Column('eval_after', sa.Float(), nullable=True),
    sa.Column('best_move_uci', sa.String(), nullable=True),
    sa.Column('best_move_san', sa.String(), nullable=True),
    sa.Column('centipawn_loss', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('game_phase', sa.String(), nullable=False),
    sa.Column('time_remaining', sa.Float(), nullable=True),
    sa.Column('tactical_motifs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'move_number')
    )
    op.create_index(op.f('ix_move_analyses_game_id'), 'move_analyses', ['game_id'], unique=False)
    op.create_table('users',
    sa.Column('lichess_username', sa.String(), nullable=True),
    sa.Column('chesscom_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('engine_depth', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_index(op.f('ix_analysis_jobs_user_id'), 'analysis_jobs', ['user_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('white_username', sa.String(), nullable=False),
    sa.Column('black_username', sa.String(), nullable=False),
    sa.Column('player_color', sa.String(), nullable=False),
    sa.Column('time_class', sa.String(), nullable=False),
    sa.Column('time_control', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('result_detail', sa.String(), nullable=True),
    sa.Column('player_rating', sa.Integer(), nullable=False),
    sa.Column('opponent_rating', sa.Integer(), nullable=False),
    sa.Column('opening_eco', sa.String(), nullable=True),
    sa.Column('opening_name', sa.String(), nullable=True),
    sa.Column('num_moves', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('platform_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', 'platform_id')
    )
    op.create_index('idx_games_opening', 'games', ['opening_eco'], unique=False)
    op.create_index('idx_games_time_class', 'games', ['time_class'], unique=False)
    op.create_index('idx_games_user_played_at', 'games', ['user_id', 'played_at'], unique=False)
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_table('puzzle_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('move_analysis_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('move_analysis_id')
    )
    op.create_index(op.f('ix_puzzle_progress_user_id'), 'puzzle_progress', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('sync_state',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_game_time', sa.DateTime(), nullable=True),
    sa.Column('cached_archives', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'platform')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_puzzle_progress_user_id'), table_name='puzzle_progress')
    op.drop_table('puzzle_progress')
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.drop_index('idx_games_user_played_at', table_name='games')
    op.drop_index('idx_games_time_class', table_name='games')
    op.drop_index('idx_games_opening', table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_analysis_jobs_user_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_move_analyses_game_id'), table_name='move_analyses')
    op.drop_table('move_analyses')
    # ### end Alembic commands ###
